### PR TITLE
Prost update

### PR DESCRIPTION
**Pull request by aectaan**
Updated dependencies

### CODE REVIEW

**Comment by barzamin** [comment]
i will test this locally later (tonight?) and merge if it's good. re: the reverted commit, i'd be happy to add a github action at some point; it's wild that people are actually using this crate.

**Comment by aectaan** [comment]
It's useful crate! Especially if you're building telegram-bot, that needs GTFS data to work. I will add PR with github action later, on weekends. Or maybe tonight

**Comment by aectaan** [comment]
Added action
Fixed example (not builds)
Cleaned codestyle with clippy

**Comment by barzamin** [comment]
thanks so much for taking care of this! looks good to me, rebased and going to merge now :)

**Pull request merged**
